//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : Alram.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class Alram extends Mode {
	private void editAlarm() {
	
	}
	
	private void saveAlarm() {
	
	}
	
	private void activeAlarm() {
	
	}
	
	private void deactiveAlarm() {
	
	}
}
