//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : Clock.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class Clock extends Mode {
	private void editTime() {
	
	}
	
	private void saveTime() {
	
	}
}
