//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : Controller.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class Controller {
	private Mode currentMode;
	private Mode disableMode;
	private bool editStatus;
	public Mode 5;
	public void reqeustNextMode() {
	
	}
	
	public void requestDisableMode() {
	
	}
	
	public void requestClockMode() {
	
	}
	
	public void requestNextAlarm() {
	
	}
	
	public void requestPrevAlarm() {
	
	}
	
	public void requestNextTimer() {
	
	}
	
	public void requestPrevTimer() {
	
	}
	
	public void requestStopAlarm() {
	
	}
	
	public void onNotiReceive() {
	
	}
}
