//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : Manager.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class Manager {
	public void OnKeyEvent() {
		//test
	}
}
