//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : Mode.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class Mode extends Manager, View {
	public void changeValue() {
	
	}
}
