//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : NotiManager.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class NotiManager extends View {
	public Array mAlarms;
	public void notify() {
	
	}
	
	public void setAlarm() {
	
	}
	
	public void removeAlarm() {
	
	}
	
	public void stopNotify() {
	
	}
}
