//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : StopWatch.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class StopWatch extends Mode, Mode, Mode, Mode, Mode {
	private Object mState;
	private Object mStartTime;
	public :½Ã°£ 4;
	private void resumeStopWatch() {
	
	}
	
	private void pauseStopWatch() {
	
	}
	
	private void resetStopWatch() {
	
	}
	
	private void updateStopwatchTime() {
	
	}
	
	private void getCurrentTime() {
	
	}
}
