//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : Timer.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class Timer extends Mode {
	private void editTimer() {
	
	}
	
	private void saveTimer() {
	
	}
	
	private void activeTimer() {
	
	}
	
	private void pauseTimer() {
	
	}
	
	private void initializeTimer() {
	
	}
	
	private void updateRemainTime() {
	
	}
}
