//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : View.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class View {
	public Date Time;
	public void draw() {
	
	}
}
