//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : AA7_2
//  @ File Name : World Watch.java
//  @ Date : 2018-11-07
//  @ Author : 
//
//




public class World Watch extends Mode {
	private Object worldcityDB;
	private Object selectedCity;
	private void editCity() {
	
	}
	
	private void saveCity() {
	
	}
}
